### PR TITLE
Complain and exit when given invalid arguments on the command line

### PR DESCRIPTION
**Pull request by olysonek**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

However, this won't compile any more for any language which is not English.

Could you fix this?

**Comment by olysonek** [comment]
I completely forgot about that, sorry! I updated the last commit. BTW is there a reason the message files aren't in UTF-8?

**Comment by olysonek** [comment]
Hi, are you planning to merge this?

**Comment by jedisct1** [comment]
Sorry, I totally forgot about this request :(

Merged!

Thanks a lot!

**Pull request merged**
