### PR TITLE
German messages enhanced

### PR DESCRIPTION
**Pull request by mlischka**
Fixed some typos, tried to unify some similar messages and translated missing messages.
_Of course, this can get improved further._

### CODE REVIEW

**Comment by kg1701** [comment]
Okay 👌 "Joe" glad we passed the test...

**Comment by kg1701** [comment]
Guys I am only laughing at myself with the "Okay Joe" comments. I am in Waaaaaaaay over my head, am in bed 20 hrs..per day, not married, kids gone and I was looking for something to occupy my time. I was in an accident in 2016 fell 30ft onto Concrete. Was Comatose over 90 days. Passed twice. You get the picture. So, was trying to self educate myself. Which believe it or not I did. But without any guidance it's rough. So I was laughing at myself, because its too advanced for me.
Please accept my apologies 🙏

Thank you all very much.

**Comment by kennyg1963** [comment]
Thank you
Moritz????
Anyway Thank you

**Comment by kennyg1963** [comment]
Thank you Frank
BTW I am Ken friends call me
"Kenny G"

**Pull request merged**
