### PR TITLE
Avoid unbalanced quotes, even in #error directives

### PR DESCRIPTION
**Pull request by SeanSEmerson**

### CODE REVIEW

**Comment by SeanSEmerson** [comment]
' breaks parsing of the file

**Comment by jedisct1** [comment]
What?

What compiler does that break?

**Comment by SeanSEmerson** [comment]
@jedisct1 
Sorry i should have been more clear, also i misspoke.

We are trying to build a docker image with pureftpd on ready to run in a container. We wish to use it in your dev environment to use as a first base before we start integrating towards external integrations. We have security confinement that requires the server to be run as non root so we try to use the flag --with-nonroot.

`FROM alpine:3.16

ARG VERSION=1.0.51

ENV PUBLIC_HOST=localhost \
    MIN_PASV_PORT=30000 \
    MAX_PASV_PORT=30009 \
    UID=1000 \
    GID=1000

RUN addgroup -S pure-ftpd && adduser -G pure-ftpd -h /var/empty -S pure-ftpd

COPY rootfs /
RUN set -ex && \
    apk add --no-cache \
        --virtual .build-deps \
        build-base \
        curl \
        openssl-dev \
        tar && \
    cd /tmp && \
    curl -sSL https://download.pureftpd.org/pub/pure-ftpd/releases/pure-ftpd-$VERSION.tar.gz | \
    tar xz --strip 1 && \
    patch -p1 src/ftpd.c minimal.patch && \
    patch -p2 src/ftpd.h maximum.patch && \
    ./configure \
        --prefix=/pure-ftpd \
        --with-nonroot \
        --with-tls && \
    make install-strip && \
    runDeps="$( \
        scanelf --needed --nobanner /usr/sbin/pure-* /usr/bin/pure-* \
            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
            | xargs -r apk info --installed \
            | sort -u \
    )" && \
    apk add --no-cache --virtual .run-deps $runDeps && \
    cd / && rm -rf /tmp/* && \
    apk del .build-deps

VOLUME /home/ftpuser /etc/pureftpd

EXPOSE 2121 $MIN_PASV_PORT-$MAX_PASV_PORT

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD /usr/sbin/pure-ftpd \
        -P $PUBLIC_HOST \
        -p $MIN_PASV_PORT:$MAX_PASV_PORT \
        -l puredb:/etc/pureftpd/pureftpd.pdb \
        -E \
        -j \` 
       It fails during make install because of that '. however we tried patching it and then we get following error 
`#8 23.16 ftpd.c: In function 'ul_check_free_space':
#8 23.16 ftpd.c:4072:19: error: storage size of 'statfsbuf' isn't known
#8 23.16  4072 |     STATFS_STRUCT statfsbuf;
#8 23.16       |                   ^~~~~~~~~
#8 23.17 ftpd.c: In function 'pureftpd_start':
#8 23.17 ftpd.c:5809:20: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]` 

If we run without --with-nonroot it installs perfectly.

**Comment by jedisct1** [comment]
So, the compiler is `gcc`.

Merged, thanks!

**Pull request merged**
