### PR TITLE
Extauth segfault

### PR DESCRIPTION
**Pull request by hudecof**
fix for #115

### CODE REVIEW

**Comment by racke** [comment]
Your first commit is completely unrelated, also "root" is not really a proper author for a commit.

**Comment by hudecof** [comment]
@racke ups, I pushed also my WIP for HAPROXY,give me few seconds to fix it

I do develop as root on my temp server, did not setup.

**Comment by racke** [comment]
> @racke ups, I pushed also my WIP for HAPROXY,give me few seconds to fix it
> 
> I do develop as root on my temp server, did not setup.

No excuse, you can simple use `git commit --author `.

**Comment by hudecof** [comment]
@racke there is new pull request #117

**Comment by racke** [comment]
:+1:

**Pull request closed without merging**
